service: serverless-node-cron

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "ses:*"
       Resource:
         - "*"
functions:
  dailyReminder:
    handler: handler.sendReminderDaily
    events:
      # invoke lambda function everyday
      - schedule: rate(1 day)
  weekendReminder:
    handler: handler.sendReminderWeekend
    events:
      # invoke lambda function every weekend 1 pm EST
      - schedule: cron(30 22 ? * SUN,SAT *)